// <auto-generated />
using System;
using TaiKhoan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DuAn2811_.Migrations
{
    [DbContext(typeof(TmdtContext))]
    partial class TmdtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DuAn2811_.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_BAO_CAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("Ghichu")
                        .HasColumnType("text")
                        .HasColumnName("GHICHU");

                    b.Property<DateOnly?>("NgayXuatBaoCao")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_XUAT_BAO_CAO");

                    b.Property<int?>("SoLuongSanPham")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_SAN_PHAM");

                    b.Property<string>("TenBaoCao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TEN_BAO_CAO");

                    b.Property<decimal?>("TongDanhThu")
                        .HasColumnType("decimal(20, 2)")
                        .HasColumnName("TONG_DANH_THU");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__BAO_CAO__3334D179FB362085");

                    b.ToTable("BAO_CAO", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHI_TIET_DON_HANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDonHang"));

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("MA_DON_HANG");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<int?>("SoLuongMua")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_MUA");

                    b.HasKey("MaChiTietDonHang")
                        .HasName("PK__CHI_TIET__8280DDB8B2E23CE1");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_DON_HANG", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHI_TIET_GIO_HANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietGioHang"));

                    b.Property<int?>("MaGioHang")
                        .HasColumnType("int")
                        .HasColumnName("MA_GIO_HANG");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.HasKey("MaChiTietGioHang")
                        .HasName("PK__CHI_TIET__D8C4F0E7A53A8B5D");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_GIO_HANG", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietKhuyenMai", b =>
                {
                    b.Property<int>("MaChiTietKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHI_TIET_KHUYEN_MAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietKhuyenMai"));

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("MA_KHUYEN_MAI");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.HasKey("MaChiTietKhuyenMai")
                        .HasName("PK__CHI_TIET__D6DAF54F1990275C");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_KHUYEN_MAI", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietSanPham", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHI_TIET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(20, 2)")
                        .HasColumnName("GIA");

                    b.Property<string>("LoaiSanPham")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LOAI_SAN_PHAM");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.Property<string>("ThuocTinh")
                        .HasColumnType("text")
                        .HasColumnName("THUOC_TINH");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__CHI_TIET__A5990A2201FC270D");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CHI_TIET_SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietXuatKho", b =>
                {
                    b.Property<int>("MaChiTietXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHI_TIET_XUAT_KHO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietXuatKho"));

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<int?>("MaXuatKho")
                        .HasColumnType("int")
                        .HasColumnName("MA_XUAT_KHO");

                    b.Property<int?>("SoLuongXuat")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_XUAT");

                    b.HasKey("MaChiTietXuatKho")
                        .HasName("PK__CHI_TIET__E1A792A5E732B09A");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaXuatKho");

                    b.ToTable("CHI_TIET_XUAT_KHO", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_Danh_Muc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_Danh_Muc");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DANH_MUC__ACC6D9BB36F3E41C");

                    b.ToTable("DANH_MUC", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.DanhSachYeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_YEU_THICH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuThich"));

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("Ma_TK");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.HasKey("MaYeuThich")
                        .HasName("PK__DANH_SAC__99D274B48230816D");

                    b.HasIndex("MaTk");

                    b.ToTable("DANH_SACH_YEU_THICH", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.DiaChiGiaoHang", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_DIA_CHI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaChi"));

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CHI_TIET");

                    b.Property<string>("HoTen")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("HO_TEN");

                    b.Property<string>("Huyen")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("HUYEN");

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("Ma_TK");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SO_DIEN_THOAI");

                    b.Property<string>("Tinh")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TINH");

                    b.Property<string>("Xa")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("XA");

                    b.HasKey("MaDiaChi")
                        .HasName("PK__DIA_CHI___3BCAD161B4A1710E");

                    b.HasIndex("MaTk");

                    b.ToTable("DIA_CHI_GIAO_HANG", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_DON_HANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("Ghichu")
                        .HasColumnType("text")
                        .HasColumnName("GHICHU");

                    b.Property<int?>("MaPhuongThuc")
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_THUC");

                    b.Property<int?>("MaPhuongThucGh")
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_THUC_GH");

                    b.Property<string>("MaTheoDoi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MA_THEO_DOI");

                    b.Property<DateOnly?>("NgayDatHang")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_DAT_HANG");

                    b.Property<decimal?>("TongDonHang")
                        .HasColumnType("decimal(20, 2)")
                        .HasColumnName("TONG_DON_HANG");

                    b.Property<string>("TrangThaiDonHang")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TRANG_THAI_DON_HANG");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DON_HANG__A7174667F23B81F3");

                    b.HasIndex("MaPhuongThuc");

                    b.HasIndex("MaPhuongThucGh");

                    b.ToTable("DON_HANG", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_GIO_HANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int?>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("Ma_TK");

                    b.Property<int?>("SoLuongSanPham")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_SAN_PHAM");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GIO_HANG__16B948AB72AFE0D1");

                    b.HasIndex("MaTk");

                    b.ToTable("GIO_HANG", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.HangSanXuat", b =>
                {
                    b.Property<int>("MaHangSanXuaT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_Hang_San_XuaT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHangSanXuaT"));

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("Ma_Danh_Muc");

                    b.Property<string>("TenHang")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Ten_Hang");

                    b.HasKey("MaHangSanXuaT")
                        .HasName("PK__HANG_SAN__891CE634389FE8E6");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("HANG_SAN_XUAT", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_KHUYEN_MAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<string>("DieuKien")
                        .HasColumnType("text")
                        .HasColumnName("DIEU_KIEN");

                    b.Property<string>("MoTaKhuyenMai")
                        .HasColumnType("text")
                        .HasColumnName("MO_TA_KHUYEN_MAI");

                    b.Property<DateOnly?>("NgayApDung")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_AP_DUNG");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_KET_THUC");

                    b.Property<int?>("SoLuongKhuyenMai")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_KHUYEN_MAI");

                    b.Property<string>("TenKhuyemMai")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TEN_KHUYEM_MAI");

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KHUYEN_M__91682CA17804E32B");

                    b.ToTable("KHUYEN_MAI", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.NhapKho", b =>
                {
                    b.Property<int>("MaNhapKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_NHAP_KHO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhapKho"));

                    b.Property<string>("DonViNhapHang")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DON_VI_NHAP_HANG");

                    b.Property<string>("GhiChi")
                        .HasColumnType("text")
                        .HasColumnName("GHI_CHI");

                    b.Property<DateOnly?>("NgayNhap")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_NHAP");

                    b.HasKey("MaNhapKho")
                        .HasName("PK__NHAP_KHO__6874D7D8A9A7E5C9");

                    b.ToTable("NHAP_KHO", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.NhapKhoChiTiet", b =>
                {
                    b.Property<int>("NhapChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NHAP_CHI_TIET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhapChiTiet"));

                    b.Property<int?>("MaNhapKho")
                        .HasColumnType("int")
                        .HasColumnName("MA_NHAP_KHO");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.HasKey("NhapChiTiet")
                        .HasName("PK__NHAP_KHO__AE1443ED0B5EB7D4");

                    b.HasIndex("MaNhapKho");

                    b.HasIndex("MaSanPham");

                    b.ToTable("NHAP_KHO_CHI_TIET", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.PhuongThucGd", b =>
                {
                    b.Property<int>("MaPhuongThucGd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_THUC_GD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongThucGd"));

                    b.Property<string>("TenPhuongThucGd")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TEN_PHUONG_THUC_GD");

                    b.HasKey("MaPhuongThucGd")
                        .HasName("PK__PHUONG_T__DD4C335A939AEC12");

                    b.ToTable("PHUONG_THUC_GD", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPhuongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_THUC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongThuc"));

                    b.Property<string>("TenPhuongThuc")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("TEN_PHUONG_THUC");

                    b.HasKey("MaPhuongThuc")
                        .HasName("PK__PHUONG_T__31662E8170FAF5F6");

                    b.ToTable("PHUONG_THUC_THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.QuanLyTonKho", b =>
                {
                    b.Property<int>("MaTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_TON_KHO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTonKho"));

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<DateOnly?>("NgayCapNhat")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_CAP_NHAT");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_TON");

                    b.HasKey("MaTonKho")
                        .HasName("PK__QUAN_LY___5CC9326D89AC93F8");

                    b.HasIndex("MaSanPham");

                    b.ToTable("QUAN_LY_TON_KHO", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("Anh")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ANH");

                    b.Property<int?>("MaHangSanXuat")
                        .HasColumnType("int")
                        .HasColumnName("Ma_Hang_San_Xuat");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("MO_TA");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TEN_SAN_PHAM");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SAN_PHAM__AEAADD69359BD171");

                    b.HasIndex("MaHangSanXuat");

                    b.HasIndex(new[] { "Anh" }, "IDX_SAN_PHAM_ANH");

                    b.HasIndex(new[] { "TenSanPham" }, "IDX_SAN_PHAM_TEN_SAN_PHAM");

                    b.ToTable("SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.SanPhamYeuThich", b =>
                {
                    b.Property<int>("MaChiTietYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHI_TIET_YEU_THICH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietYeuThich"));

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int")
                        .HasColumnName("MA_SAN_PHAM");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.HasKey("MaChiTietYeuThich")
                        .HasName("PK__SAN_PHAM__CC600104CF93BB80");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SAN_PHAM_YEU_THICH", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.TaiKHoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ma_TK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTk")
                        .HasName("PK__TAI_kHOA__2E62FB7C5190AE69");

                    b.HasIndex(new[] { "MatKhau" }, "IDX_TAI_KHOAN_MK");

                    b.HasIndex(new[] { "TenDangNhap" }, "IDX_TAI_KHOAN_TEN");

                    b.ToTable("TAI_kHOAN", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_THANH_TOAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("MA_DON_HANG");

                    b.Property<int?>("MaPhuongThuc")
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_THUC");

                    b.Property<int?>("MaPhuongThucGh")
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_THUC_GH");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_THANH_TOAN");

                    b.Property<decimal?>("SoTienCanThanhToan")
                        .HasColumnType("decimal(20, 2)")
                        .HasColumnName("SO_TIEN_CAN_THANH_TOAN");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TRANG_THAI");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__THANH_TO__D82DF910AE59EE27");

                    b.HasIndex("MaDonHang");

                    b.ToTable("THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.XuatKho", b =>
                {
                    b.Property<int>("MaXuatKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_XUAT_KHO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXuatKho"));

                    b.Property<string>("DonViXuatKho")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DON_VI_XUAT_KHO");

                    b.Property<string>("GhiChi")
                        .HasColumnType("text")
                        .HasColumnName("GHI_CHI");

                    b.Property<DateOnly?>("NgayXuat")
                        .HasColumnType("date")
                        .HasColumnName("NGAY_XUAT");

                    b.HasKey("MaXuatKho")
                        .HasName("PK__XUAT_KHO__36F544112A26A70F");

                    b.ToTable("XUAT_KHO", (string)null);
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("DuAn2811_.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK__CHI_TIET___MA_DO__5AEE82B9");

                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__CHI_TIET___MA_SA__5BE2A6F2");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("DuAn2811_.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .HasConstraintName("FK__CHI_TIET___MA_GI__4D94879B");

                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__CHI_TIET___MA_SA__4CA06362");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("DuAn2811_.Models.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK__CHI_TIET___MA_KH__6383C8BA");

                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__CHI_TIET___MA_SA__6477ECF3");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__CHI_TIET___MA_SA__412EB0B6");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.ChiTietXuatKho", b =>
                {
                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietXuatKhos")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__CHI_TIET___MA_SA__72C60C4A");

                    b.HasOne("DuAn2811_.Models.XuatKho", "MaXuatKhoNavigation")
                        .WithMany("ChiTietXuatKhos")
                        .HasForeignKey("MaXuatKho")
                        .HasConstraintName("FK__CHI_TIET___MA_XU__71D1E811");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaXuatKhoNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.DanhSachYeuThich", b =>
                {
                    b.HasOne("DuAn2811_.Models.TaiKHoan", "MaTkNavigation")
                        .WithMany("DanhSachYeuThiches")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__DANH_SACH__Ma_TK__440B1D61");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.DiaChiGiaoHang", b =>
                {
                    b.HasOne("DuAn2811_.Models.TaiKHoan", "MaTkNavigation")
                        .WithMany("DiaChiGiaoHangs")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__DIA_CHI_G__Ma_TK__5441852A");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.DonHang", b =>
                {
                    b.HasOne("DuAn2811_.Models.PhuongThucThanhToan", "MaPhuongThucNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaPhuongThuc")
                        .HasConstraintName("FK__DON_HANG__MA_PHU__571DF1D5");

                    b.HasOne("DuAn2811_.Models.PhuongThucGd", "MaPhuongThucGhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaPhuongThucGh")
                        .HasConstraintName("FK__DON_HANG__MA_PHU__5812160E");

                    b.Navigation("MaPhuongThucGhNavigation");

                    b.Navigation("MaPhuongThucNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.GioHang", b =>
                {
                    b.HasOne("DuAn2811_.Models.TaiKHoan", "MaTkNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaTk")
                        .HasConstraintName("FK__GIO_HANG__Ma_TK__49C3F6B7");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.HangSanXuat", b =>
                {
                    b.HasOne("DuAn2811_.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("HangSanXuats")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("FK__HANG_SAN___Ma_Da__3B75D760");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.NhapKhoChiTiet", b =>
                {
                    b.HasOne("DuAn2811_.Models.NhapKho", "MaNhapKhoNavigation")
                        .WithMany("NhapKhoChiTiets")
                        .HasForeignKey("MaNhapKho")
                        .HasConstraintName("FK__NHAP_KHO___MA_NH__6C190EBB");

                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("NhapKhoChiTiets")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__NHAP_KHO___MA_SA__6D0D32F4");

                    b.Navigation("MaNhapKhoNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.QuanLyTonKho", b =>
                {
                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("QuanLyTonKhos")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__QUAN_LY_T__MA_SA__6754599E");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.SanPham", b =>
                {
                    b.HasOne("DuAn2811_.Models.HangSanXuat", "MaHangSanXuatNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaHangSanXuat")
                        .HasConstraintName("FK__SAN_PHAM__Ma_Han__3E52440B");

                    b.Navigation("MaHangSanXuatNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.SanPhamYeuThich", b =>
                {
                    b.HasOne("DuAn2811_.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("SanPhamYeuThiches")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK__SAN_PHAM___MA_SA__46E78A0C");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.ThanhToan", b =>
                {
                    b.HasOne("DuAn2811_.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK__THANH_TOA__MA_DO__5EBF139D");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("DuAn2811_.Models.DanhMuc", b =>
                {
                    b.Navigation("HangSanXuats");
                });

            modelBuilder.Entity("DuAn2811_.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("DuAn2811_.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DuAn2811_.Models.HangSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DuAn2811_.Models.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("DuAn2811_.Models.NhapKho", b =>
                {
                    b.Navigation("NhapKhoChiTiets");
                });

            modelBuilder.Entity("DuAn2811_.Models.PhuongThucGd", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("DuAn2811_.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("DuAn2811_.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("ChiTietSanPhams");

                    b.Navigation("ChiTietXuatKhos");

                    b.Navigation("NhapKhoChiTiets");

                    b.Navigation("QuanLyTonKhos");

                    b.Navigation("SanPhamYeuThiches");
                });

            modelBuilder.Entity("DuAn2811_.Models.TaiKHoan", b =>
                {
                    b.Navigation("DanhSachYeuThiches");

                    b.Navigation("DiaChiGiaoHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("DuAn2811_.Models.XuatKho", b =>
                {
                    b.Navigation("ChiTietXuatKhos");
                });
#pragma warning restore 612, 618
        }
    }
}
